version: "3.6"
services:
  database:
    image: mysql:5
    container_name: database
    restart: always
    ports:
      - target: 3306
        published: 3306
        protocol: tcp
        mode: host
    environment:
      MYSQL_ROOT_PASSWORD: inet2005
      TZ: America/Halifax
    volumes:
      # scripts in the database-scripts folder are executed to create various sample databases
      - ./database-scripts:/docker-entrypoint-initdb.d
      - ./database-scripts:/home/database-scripts
  webserver:
    depends_on:
      - database
    build:
      context: ./dockerfiles/webserver
    image: nscc-php/webserver:v2021
    container_name: webserver
    restart: always
    ports: 
      - "80:80"
    volumes:
      - ../wwwroot:/var/www/html 
  phpmyadmin:
    depends_on:
      - database
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: inet2005
